### ISSUE TITLE
There is a new version of web-component-tester-custom-runner 6.1.1

### ISSUE THREAD

**Issue by toshovski** [hotforfeature/wct-browserstack#5]
I tried out to install wct-browserstack, but requires web-component-tester-custom-runner@6.1.0. There is a newer 6.1.1 version and the wct-browserstack requires 6.1.0.

npm WARN deprecated @types/assert@0.0.29: See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12826
/usr/lib
├── wct-browserstack@0.2.1 
└── UNMET PEER DEPENDENCY web-component-tester-custom-runner@^6.1.0

**Comment by hotforfeature** [comment]
It's a peer dependency, it won't automatically install like normal dependencies. Did you try `npm install --save-dev web-component-tester-custom-runner`?

**Comment by toshovski** [comment]
yes, but it installs 6.1.1 I had to manually install the 6.1.0.

**Comment by hotforfeature** [comment]
6.1.1 is the correct version. The requirement is for `^6.1.0`, which will install the latest 6.1.x version.

**Comment by toshovski** [comment]
this is strange. I tried it out and got an error, that is 6.1.0 expected. I had to uninstall the 6.1.1 and installed 6.1.0

**Comment by hotforfeature** [comment]
If you use 6.1.0, the plugin will not work. You must use 6.1.1.
